# Universal sample rate
sample_rate: 44100

# Universal number of channels
channels: 1

# Samples per window for score follower
win_length: 4096

# Samples per hop for score follower. This should be the same as WIN_LENGTH for now.
# Can add support for different values in the future
hop_length: 4096

# Search width for score follower. Higher values are more computationally expensive
c: 50

# Slope constraint for score follower. 1 / MAX_RUN_COUNT <= slope <= MAX_RUN_COUNT
max_run_count: 3

# Weight for the diagonal in the cost matrix for score follower.
# Values less than 2 bias toward diagonal steps
diag_weight: 0.75

# Maximum duration of audio buffer in seconds
max_duration: 600

# Type of feature to use for alignment
feature_type: "CENS"

# Volume multiplier for solo instrument
solo_volume_multiplier: 1.05

# Instrument number in MIDI score of accompaniment part (set to 0 to copy solo)
accomp_instr_index: 1

# Instrument sound (MIDI program number, 1=piano, 43=cello) for accompaniment part
accomp_program_num: 43

# Tempo at which the user plans to play in BPM
ref_tempo: 100

# Tempo at which the user actually plays in BPM
live_tempo: 110

# Set to true to use microphone input, false to use prerecorded soloist audio
use_mic: false

# Set to true to only compute alignment w/o playback, not compatible with use_mic
skip_playback: false

# Name of piece - if provided, paths will be auto-generated from this
piece_name: ode_to_joy
# Otherwise, supply all three paths below manually

# Uncomment and set these paths if piece_name is not provided
# path_midi_score: data/midi/your_piece.mid
# path_ref_wav: data/audio/your_piece/ref_100bpm.wav
# path_live_wav: data/audio/your_piece/live_110bpm.wav

# Soundfont (looks for a soundfont under the 'soundfonts' folder)
soundfont_filename: FluidR3_GM.sf2
# Uncomment and set soundfont path if soundfont_filename is not provided
# path_soundfont: soundfonts/FluidR3_GM.sf2
