name: Auto Test Python Code
 
on:
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests to the main branch
 
jobs:
  test:
    runs-on: ${{ matrix.os }}  # Run the tests on the same matrix of operating systems
    strategy:
      matrix:
        os: [ubuntu-latest]  # Only run on Ubuntu for testing
        # os: [ubuntu-latest, windows-latest, macos-latest]
 
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # using the version specified in conda env

      # this rule configures gitHub environment to install all dependencies
      # install portaudio19 (cross-platform audio I/O library) required by pyaudio
      - name: install dependencies
        working-directory: backend
        run: |  
          sudo apt install portaudio19-dev python3-pyaudio
          sudo apt install fluid-soundfont-gm
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      # Run tests present in module_tests/
      - name: Run tests
        working-directory: backend
        # Run the tests in module_tests/ using the unittest module
        run: |
            # edit by nick: using CI_test_runner.py
            python ./CI_test_runner.py
       # Getting coverage score
      - name: Coverage
        run: |
      #       coverage run ./CI_test_runner.py
      #       coverage report
