name: lint frontend code with eslint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code to be merged with main
        uses: actions/checkout@v3
      
      - name: Install dependencies
        working-directory: frontend/companion-app
        run: npm install
    
      - name: Format with prettier before linting
        working-directory: frontend/companion-app
        run: npm run format

      - name: Run ESLint
        working-directory: frontend/companion-app
        run: npm run lint